spring:
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health,info


server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax


springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha